name: 'check if test'
description: 'check run'
inputs:
  conclusion:  # id of input
    description: 'of the test'
    required: true
    default: 'failure'
  author:
    description: 'name'
    required: true
    default: 'anyone'
  myToken:
    description: 'github token'
    required: true
    default: 'none'
  head_sha:
    description: 'head_sha'
    required: true
    default: 'none'
outputs:
  checkRun:
    description: 'of this test'
runs:
  using: 'node12'
  main: 'index.js'
